# Generated by Django 6.0 on 2025-12-14 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('company', models.CharField(blank=True, max_length=200)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_read', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Contact Submission',
                'verbose_name_plural': 'Contact Submissions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DemoRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('company', models.CharField(max_length=200)),
                ('role', models.CharField(blank=True, max_length=200)),
                ('segment', models.CharField(choices=[('grower', 'Grower'), ('processor', 'Food Processor'), ('cpg', 'CPG Producer'), ('restaurant', 'Restaurant / Foodservice'), ('government', 'Government / Institution'), ('investor', 'Investor'), ('ag_supply', 'Ag Supply / Input Supplier'), ('other', 'Other')], max_length=50)),
                ('goals', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('new', 'New'), ('contacted', 'Contacted'), ('scheduled', 'Demo Scheduled'), ('completed', 'Demo Completed'), ('closed', 'Closed')], default='new', max_length=20)),
                ('notes', models.TextField(blank=True, help_text='Internal notes about this lead')),
            ],
            options={
                'verbose_name': 'Demo Request',
                'verbose_name_plural': 'Demo Requests',
                'ordering': ['-created_at'],
            },
        ),
    ]
